CREATE TABLE IF NOT EXISTS `mobium_registration_fields` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SLUG` varchar(255) NOT NULL,
  `EDITABLE` char(1) NOT NULL DEFAULT 'N',
  `REGISTER_ACTIVE` char(1) NOT NULL DEFAULT 'N',
  `REGISTER_REQUIRED` char(1) NOT NULL DEFAULT 'N',
  `REGISTER_TYPE` varchar(30) DEFAULT NULL,
  `REGISTER_TITLE` varchar(255) NOT NULL,
  `REGISTER_SORT` int(11) NOT NULL DEFAULT '500',
  `VERIFICATION_ACTIVE` char(1) NOT NULL DEFAULT 'N',
  `VERIFICATION_TIME` int(11) DEFAULT NULL,
  `VERIFICATION_TEXT` varchar(255) DEFAULT NULL,
  `VERIFICATION_TYPE` varchar(30) DEFAULT NULL,
  `VERIFICATION_DRIVER` varchar(30) DEFAULT NULL,
  `PROFILE_ACTIVE` char(1) NOT NULL DEFAULT 'N',
  `PROFILE_SORT` int(11) NOT NULL DEFAULT '500',
  `PROFILE_TYPE` varchar(30) DEFAULT NULL,
  `PROFILE_ACTION` varchar(50) DEFAULT NULL,
  `PROFILE_ACTION_PARAM` text,
  `PROFILE_TITLE` varchar(255) DEFAULT NULL,
  `RESTORE_ACTIVE` char(1) NOT NULL DEFAULT 'N',
  `RESTORE_SORT` int(11) NOT NULL DEFAULT '500',
  PRIMARY KEY (`ID`),
  KEY `REGISTER_ACTIVE` (`REGISTER_ACTIVE`),
  KEY `PROFILE_ACTIVE` (`PROFILE_ACTIVE`)
);

CREATE TABLE IF NOT EXISTS `mobium_user_token`(
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BODY` varchar(50)  NOT NULL,
  `CREATED_AT` int(11) NOT NULL,
  `LIFETIME` int(11) DEFAULT 0,
  `TYPE` varchar(50) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `mobium_verify`(
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(50) NOT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  `LIFETIME` int(11) DEFAULT 180,
  `APP_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `mobium_delivery_type_assoc`(
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE` char(1) NOT NULL DEFAULT 'N',
  `DELIVERY_SERVICE_ID_BITRIX` varchar(100) NOT NULL,
  `DELIVERY_SERVICE_ID_MOBIUM` varchar (100)  NOT NULL,
  `DELIVERY_SERVICE_AREA_ID` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `mobium_offers_export_props`(
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXPORT_PROP_ID` VARCHAR(255)  NOT NULL,
  `EXPORT_PROP` char(1)  NOT NULL DEFAULT 'Y',
  `EXPORT_NAME` varchar(255)  NULL,
  `EXPORT_SORT` int(11) NOT NULL DEFAULT 500,
  `PROP_IS_VENDOR_CODE` char(1)  NOT NULL DEFAULT 'N',
  `PROP_IS_TOOLTIP` char(1)  NOT NULL DEFAULT 'N',
  `TOOLTIP_OPTIONS` TEXT NULL,

  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `mobium_products_export_props`(
   `ID` int(11) NOT NULL AUTO_INCREMENT,
   `EXPORT_PROP_ID` VARCHAR(255)  NOT NULL,
   `EXPORT_PROP` char(1)  NOT NULL DEFAULT 'Y',
   `EXPORT_NAME` varchar(255)  NULL,
   `EXPORT_SORT` int(11) NOT NULL DEFAULT 500,
   `PROP_IS_VENDOR_CODE` char(1)  NOT NULL DEFAULT 'N',
   `PROP_IS_TOOLTIP` char(1)  NOT NULL DEFAULT 'N',
   `TOOLTIP_OPTIONS` TEXT NULL,

   PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `mobium_register_session`(
   `ID` int(11) NOT NULL AUTO_INCREMENT,
   `APP_ID` INT(11) NOT NULL,
   `CREATED_AT` INT(11) NOT NULL,
   `DATA` TEXT NULL,
   PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `mobium_auth_tries`(
    `APP_ID` int(11) NOT NULL,
    `DATA` TEXT NULL,
    PRIMARY KEY (`APP_ID`)
);