CREATE TABLE `mobium_offers_export_props`(
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXPORT_PROP_ID` VARCHAR(255) COLLATE utf8_general_ci NOT NULL,
  `EXPORT_PROP` char(1) COLLATE utf8_general_ci NOT NULL DEFAULT 'Y',
  `EXPORT_NAME` varchar(255) COLLATE utf8_general_ci NULL,
  `EXPORT_SORT` int(11) NOT NULL DEFAULT 500,
  `PROP_IS_VENDOR_CODE` char(1) COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `PROP_IS_TOOLTIP` char(1) COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
  `TOOLTIP_OPTIONS` TEXT NULL,

  PRIMARY KEY (`ID`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `mobium_products_export_props`(
   `ID` int(11) NOT NULL AUTO_INCREMENT,
   `EXPORT_PROP_ID` VARCHAR(255) COLLATE utf8_general_ci NOT NULL,
   `EXPORT_PROP` char(1) COLLATE utf8_general_ci NOT NULL DEFAULT 'Y',
   `EXPORT_NAME` varchar(255) COLLATE utf8_general_ci NULL,
   `EXPORT_SORT` int(11) NOT NULL DEFAULT 500,
   `PROP_IS_VENDOR_CODE` char(1) COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
   `PROP_IS_TOOLTIP` char(1) COLLATE utf8_general_ci NOT NULL DEFAULT 'N',
   `TOOLTIP_OPTIONS` TEXT NULL,

   PRIMARY KEY (`ID`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
